[build]
builder = "dockerfile"

[[services]]
name = "backend"
dockerfile = "backend/Dockerfile"
startCommand = "npm start"

[[services]]
name = "frontend"
dockerfile = "frontend/Dockerfile"
startCommand = "serve -s dist -l 3000"
