[build]
builder = "nixpacks"

[[services]]
name = "backend"
startCommand = "npm start"
rootDirectory = "backend"

[[services]]
name = "frontend"
startCommand = "npm run preview"
rootDirectory = "frontend"
